### ISSUE TITLE
line counter will need to be added 1 more

### ISSUE THREAD

**Issue by jonnyr2008** [UltimatePea/CSE11StyleChecker#10]
grep -n '.\{81,\}' [Filename] allows one more character in line.
This is also confirmed when I use other way to check the character number.

So,  in here when output says 81 characters, that is actually 80.

**Comment by UltimatePea** [comment]
Is it the same issue as #3 or not?

**Comment by venkr** [comment]
As UltimatePea just said, change #4 made after issue #3 was raised should have fixed it.

grep -n '.{81,}' should match any group of 81 non-EOL characters (ie: return true if more than 80 non-EOL characters), and we now check for whether a line has more than 80 characters excluding the EOL character.

If it still seems to be broken, give an example input line that causes the error if possible.

**Comment by jonnyr2008** [comment]
Yep they are the same, but one more thing here. for indentation, can you just set it to be multiples of 2 not 4?

**Comment by jonnyr2008** [comment]
sorry indentation

**Comment by UltimatePea** [comment]
The current indentation setting is 2 paces per block of code

**Comment by jonnyr2008** [comment]
It currently only accepts consecutive multiples of 2, but if sometimes, the multiples are even, there will be an error.

**Comment by UltimatePea** [comment]
Could you please provide an example of your case

**Comment by jonnyr2008** [comment]
Checking file : Direction.java
Line 14: Potentially Wrong Indentation Expected 2 Actual 4
Line 24: Potentially Wrong Indentation Expected 4 Actual 8
Line 25: Potentially Wrong Indentation Expected 2 Actual 4
Line 34: Potentially Wrong Indentation Expected 6 Actual 12
Line 35: Potentially Wrong Indentation Expected 6 Actual 12
Line 36: Potentially Wrong Indentation Expected 6 Actual 12
Line 37: Potentially Wrong Indentation Expected 6 Actual 12
Line 38: Potentially Wrong Indentation Expected 4 Actual 8
Line 48: Potentially Wrong Indentation Expected 6 Actual 12
Line 49: Potentially Wrong Indentation Expected 6 Actual 12
Line 50: Potentially Wrong Indentation Expected 6 Actual 12
Line 51: Potentially Wrong Indentation Expected 6 Actual 12
Line 52: Potentially Wrong Indentation Expected 4 Actual 8
Line 62: Potentially Wrong Indentation Expected 6 Actual 12
Line 63: Potentially Wrong Indentation Expected 6 Actual 12
Line 64: Potentially Wrong Indentation Expected 6 Actual 12
Line 65: Potentially Wrong Indentation Expected 6 Actual 12
Line 66: Potentially Wrong Indentation Expected 4 Actual 8
Checking file : EC_SnakeController.java
729 lines checked, everything fine. Total 73 double slash comments
Checking file : EC_Snake.java
Line 285: Potentially Wrong Indentation Expected 8 Actual 10
Line 286: Potentially Wrong Indentation Expected 6 Actual 8
Line 289: Potentially Wrong Indentation Expected 4 Actual 6
Checking file : PA8Strings.java
Line 10: Potentially Wrong Indentation Expected 2 Actual 4
Line 13: Potentially Wrong Indentation Expected 2 Actual 4
Line 16: Potentially Wrong Indentation Expected 2 Actual 4
Line 19: Potentially Wrong Indentation Expected 2 Actual 4
Line 21: Potentially Wrong Indentation Expected 2 Actual 4
Line 23: Potentially Wrong Indentation Expected 2 Actual 4
Line 25: Potentially Wrong Indentation Expected 2 Actual 4
Line 27: Potentially Wrong Indentation Expected 2 Actual 4
Line 29: Potentially Wrong Indentation Expected 2 Actual 4
Line 31: Potentially Wrong Indentation Expected 2 Actual 4
Checking file : SnakeController.java
696 lines checked, everything fine. Total 71 double slash comments
Checking file : Snake.java
Line 282: Potentially Wrong Indentation Expected 8 Actual 10
Line 283: Potentially Wrong Indentation Expected 6 Actual 8
Line 286: Potentially Wrong Indentation Expected 4 Actual 6
34 errors total

**Comment by UltimatePea** [comment]
That is because their indentation level is 4 spaces, but this script assumes two spaces. It is good to consider additional customization though.

**Comment by jonnyr2008** [comment]
OK I see
