### ISSUE TITLE
Python include fails on some devices

### ISSUE THREAD

**Issue by venkr** [UltimatePea/CSE11StyleChecker#5]
I get the following error on OSX:
`-bash: ./stylecheck: /software/common64/python/bin/python: bad interpreter: No such file or directory`

A potential fix seems to be replacing "#!software/common64/python/bin/python" with "#!usr/bin/python". That allows it to work on OSX, but causes it to stop working on the unix lab computers though.

**Comment by UltimatePea** [comment]
I included the path of the python interpreter on lab computes. Got to make a change to the interpreter path of the source file on OS X.  Or is it a good idea to just prepend the command with a explicit python interpreter.

```
python stylecheck *.java
```

**Comment by UltimatePea** [comment]
Updated README. The problem should be resolved.
