### ISSUE TITLE
'Everything fine' message issues

### ISSUE THREAD

**Issue by venkr** [UltimatePea/CSE11StyleChecker#7]
Consider a test case where there are three files: 1,2,3 and files 1,3 are perfect, but 2 has issues. 
Current functionality means file 1 will print an everything fine message, but file 3 will not do so because the error count is non-zero due to 2.

Pull request submitted which should solve this through maintaining a boolean value for each file which stores whether the specific file has an error or not.

**Comment by UltimatePea** [comment]
Fixed  761d265, Thanks for help!!
